[pipeline]
name = "charisma"
version = "0.1.0"
model = "openai/gpt-5"
provider = "openai/default"
input_csv = "inputs/goals_openai.csv"
behavioral_coding_csv="inputs/behavioral_coding.csv"
[pipeline.setup_goals]
input_csv = "inputs/Human_Goals_List_Clean_Updated.csv"
output_csv = "outputs/goals_openai.csv"
num_records = 135
[pipeline.scenario_generation]
difficulty = "Hard" # TODO: Difficulty levels should be defined as a list
agentic_generation = false
[pipeline.interaction_generation]
scenarios_filepath = "inputs/goals_deepseek__scenario_generation_Easy.csv"
characters_filepath = "inputs/characters.csv"
[pipeline.evaluation]
input_csv = "outputs/goals_deepseek__scenario_generation_medium__interaction_generation.csv"
[pipeline.experiments.robustness_1]
easy_scenario_csv="inputs/goals_deepseek__scenario_generation_Easy.csv"
hard_scenario_csv="inputs/goals_deepseek__scenario_generation_Hard.csv"
characters_filepath="inputs/characters.csv"
num_scenarios=50
num_agent_pairs=50
agent_per_pair=5
num_repeats=5
[pipeline.experiments.personality_ga]
easy_scenario_csv="inputs/goals_deepseek__scenario_generation_Easy.csv"
hard_scenario_csv="inputs/goals_deepseek__scenario_generation_Hard.csv"
characters_filepath="inputs/characters.csv"
include_categories=["Cooperation", "Conflict Resolution"]
n_scenario_reps=7
max_pair_overall=2
max_pair_per_cell=1
pairs_output_csv="outputs/personality_ga/pairs.csv"
assignment_output_csv="outputs/personality_ga/assignment_manifest.csv"
results_csv="outputs/personality_ga/results.csv"